### ISSUE TITLE
Not redirecting to call back url

### ISSUE THREAD

**Issue by titusfrezer** [Chapa-Et/sdk-examples#1]
After I made the payment using the checkout URL, it is not redirecting me to the call back URL I give It just stuck with the payment is successful confirmation.
![image](https://user-images.githubusercontent.com/53559440/188853845-4689a9e4-5ddf-4f20-a5ec-5fa54ca86e37.png)

**Comment by isrugeek** [comment]
Hi @titusfrezer,

I tried it with both `return_url` and `callback_url`. If you want to redirect your customer after the payment is made, use `return_url` [since it is a web address to redirect the user after payment is successful](https://developer.chapa.co/docs/accept-payments/). But the purpose of `callback_url` here is to call a function that runs when payment is successful. 

I will close this issue now, and feel free to reopen it if you have any questions.
